version: '3.5'
services:
  idoctorbackend:
    ports:
      - "8080:8080"
    container_name: idoctorbackend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - sqlserver

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd!