services:
  idoctorbackend:
    ports:
      - "8080:8080"
    container_name: idoctorbackend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
        - sqlserver
        - migrations

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 1435:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd!
   
  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: DockerfileMigration
    depends_on:
        - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production